name: Coverage
on: [push]
permissions: read-all
jobs:
  goversion:
    uses: ./.github/workflows/go-version.yaml
  coverage:
    runs-on: ubuntu-latest
    needs: goversion
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-amd64-coverage
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: ${{ needs.goversion.outputs.goversion }}
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        mkdir "${TARGET}"
        case "${TARGET}" in
          linux-amd64-coverage)
            GOARCH=amd64 ./scripts/codecov_upload.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
